"""Outbound client to the identity component.

Two surfaces:

  - Looking up a Eugene `personId` for a `(platform, account_id)` pair
    so an adapter can decide whether to file a pending link or forward
    the message to the orchestrator.

  - Filing a new `PendingIdentityLink` when an unknown platform user
    talks to Eugene for the first time. The operator approves later
    via the UI.

v0.2 doesn't have a dedicated "lookup by alias" endpoint on identity
— the workaround is to list all persons and check their `aliases[]`.
Personal-install scale, single-digit persons, single-digit aliases.
When that becomes painful (v0.3+?) we'll add a focused lookup endpoint.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import UUID

import httpx

from .._generated.common_models import PendingIdentityLink, Person, Status1


class IdentityClient:
    def __init__(
        self,
        *,
        base_url: str,
        timeout_seconds: float = 30.0,
        service_token: str | None = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        headers = {"Authorization": f"Bearer {service_token}"} if service_token else None
        self._client = httpx.AsyncClient(
            base_url=self._base_url,
            timeout=httpx.Timeout(timeout_seconds, connect=10.0),
            headers=headers,
        )

    @property
    def base_url(self) -> str:
        return self._base_url

    async def list_persons(self) -> list[Person]:
        response = await self._client.get("/v1/identity/persons")
        response.raise_for_status()
        body = response.json()
        return [Person.model_validate(p) for p in body.get("persons", [])]

    async def resolve_person_by_alias(self, *, platform: str, account_id: str) -> UUID | None:
        """Find a personId by `(platform, account_id)` alias. Returns
        None when no alias matches — adapter must file a pending link."""
        persons = await self.list_persons()
        for person in persons:
            for alias in person.aliases or []:
                if alias.platform == platform and alias.accountId == account_id:
                    return person.personId
        return None

    async def file_pending_link(
        self,
        *,
        platform: str,
        account_id: str,
        handle: str | None,
        display_name: str | None,
        avatar_url: str | None,
        triggering_message: str,
        adapter_private: dict[str, Any] | None = None,
    ) -> bool:
        """POST /v1/identity/links/pending.

        Returns True on 201 or 409 (link already pending — adapter
        retried; identity treats this as success per the spec).
        Returns False on other failures (logs them; the adapter falls
        through to silently dropping the message — Eugene doesn't
        respond to unknown people).

        `linkId` is server-generated by identity (the route ignores
        client-supplied values to prevent collisions); we send a
        placeholder UUID4 here just to satisfy the model required-
        fields validator.
        """
        from uuid import uuid4

        link = PendingIdentityLink(
            linkId=uuid4(),
            platform=platform,
            accountId=account_id,
            handle=handle,
            displayName=display_name,
            avatarUrl=avatar_url,
            firstSeen=datetime.now(UTC),
            triggeringMessage=triggering_message,
            status=Status1.pending,
            adapterPrivate=adapter_private,
        )
        response = await self._client.post(
            "/v1/identity/links/pending",
            json=link.model_dump(mode="json", exclude_none=True),
        )
        return response.status_code in (200, 201, 409)

    async def aclose(self) -> None:
        await self._client.aclose()
